spring:
  datasource:
    url: jdbc:h2:mem:person
    username: art
    password: art
    driverClassName: org.h2.Driver
  h2.console.enable: true
  h2.console.path: /h2-console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: drop-and-create #validate
  application:
    name: cad-person-api
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  servlet:
    context-path: /cad-person-api
  port: 8082